next-version: 1.0.0
branches:
  main:
    regex: ^master$|^main$
    mode: ContinuousDelivery
    label: ""
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    source-branches: ["develop", "release"]
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
    pre-release-weight: 55000
  feature:
    regex: ^features?[/-]
    mode: ContinuousDelivery
    label: "{BranchName}"
    increment: Inherit
    source-branches:
      ["develop", "main", "release", "feature", "support", "hotfix"]
    pre-release-weight: 30000
  pull-request:
    regex: ^(pull|pull\-requests|pr)[/-]
    mode: ContinuousDelivery
    label: PullRequest
    increment: Inherit
    label-number-pattern: '[/-](?<number>\d+)[-/]'
    source-branches:
      ["develop", "main", "release", "feature", "support", "hotfix"]
    pre-release-weight: 30000
  hotfix:
    regex: ^hotfix(es)?[/-]
    mode: ContinuousDelivery
    label: beta
    increment: Inherit
    source-branches: ["release", "main", "support", "hotfix"]
    pre-release-weight: 30000