name: CI Pipeline
on:
  push:
    branches:
      - develop
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Print current path before start script
        run: |
          echo "Full path to publish directory:"
          pwd
          
      - name: Print files in the current directory
        run: |
          echo "Files in the current directory:"
          ls
          
      - name: Restore
        run: dotnet restore
      
      - name: Format check
        run: dotnet format --verify-no-changes --verbosity normal
      
      - name: Build
        run: dotnet build --configuration Release
      
      - name: Publish
        run: dotnet publish --configuration Release --output ./publish/quiz-master/
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: published-quiz-master
          path: "$(pwd)/publish/quiz-master/"