name: CI Pipeline
on:
  push:
    branches:
      - develop
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Restore
        if: success()
        run: dotnet restore
      
      - name: Format check
        if: success()
        run: dotnet format --verify-no-changes --verbosity normal
      
      - name: Build
        if: success()
        run: dotnet build --configuration Release
      
      - name: Publish
        if: success()
        run: dotnet publish --configuration Release --output ./publish/quiz-master/
      
      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: published-quiz-master
          path: ./publish/quiz-master/