name: CI Pipeline

on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Restore
        run: dotnet restore
      
      - name: Format check
        run: dotnet format --verify-no-changes --verbosity normal
      
      - name: Build
        run: dotnet build src/GameHub.QuizMaster/GameHub.QuizMaster.csproj --configuration Release
      
      - name: Run Test
        run: dotnet test tests/GameHub.QuizMaster.Tests/GameHub.QuizMaster.Tests.csproj